/* data.js — the deck
 * POSITION: { id, name, people(1-5; 5=orgy), cats[], diff(1-5), pose, flip?,
 *             needsToy?, tagline, steps[], tip }
 * Adult educational content; tone is practical and comfort/consent-first.
 */
window.PEOPLE = {
  1: { label: "Solo",   emoji: "👤" },
  2: { label: "Couple", emoji: "❤️" },
  3: { label: "Three",  emoji: "👥" },
  4: { label: "Four",   emoji: "👨‍👩‍👧" },
  5: { label: "Orgy",   emoji: "🎉" }
};

window.CATEGORIES = {
  beginner: { label: "Beginner",  color: "#39d98a" },
  intimate: { label: "Intimate",  color: "#ff6fae" },
  ontop:    { label: "On Top",    color: "#ff4d8d" },
  rear:     { label: "Rear",      color: "#ff8c42" },
  side:     { label: "Side/Lazy", color: "#6fc7ff" },
  seated:   { label: "Seated",    color: "#c08bff" },
  standing: { label: "Standing",  color: "#3fd0ff" },
  oral:     { label: "Oral",      color: "#ffd23f" },
  anal:     { label: "Anal",      color: "#9b5cff" },
  athletic: { label: "Athletic",  color: "#ff5b7f" },
  kinky:    { label: "Kinky",     color: "#ff3d6e" },
  toys:     { label: "Toys",      color: "#5ce0c8" },
  quickie:  { label: "Quickie",   color: "#ffa64d" }
};

window.MODIFIERS = [
  { kind: "Location", text: "Move to the floor" },
  { kind: "Location", text: "Take it to the shower" },
  { kind: "Location", text: "Against the nearest wall" },
  { kind: "Location", text: "On a chair" },
  { kind: "Location", text: "Edge of the bed" },
  { kind: "Sensory",  text: "Blindfold one of you" },
  { kind: "Sensory",  text: "Lights off — go by touch" },
  { kind: "Sensory",  text: "Add something cold (ice)" },
  { kind: "Sensory",  text: "One person stays totally still" },
  { kind: "Tempo",    text: "Slow motion for 2 minutes" },
  { kind: "Tempo",    text: "Edge — stop just before the finish" },
  { kind: "Tempo",    text: "Hold eye contact the whole time" },
  { kind: "Dare",     text: "Add a toy of your choice" },
  { kind: "Dare",     text: "Swap who's in control halfway" },
  { kind: "Dare",     text: "Dirty talk only — no laughing" },
  { kind: "Dare",     text: "Loser of rock-paper-scissors bottoms" }
];

window.POSITIONS = [
  // ===================== SOLO (1) =====================
  { id:"solo-classic", name:"Classic Solo", people:1, cats:["beginner"], diff:1, pose:"soloRecline",
    tagline:"Lie back and take your time.", steps:["Get comfortable lying back, fully relaxed.","Start slow and build — no rush, no goal.","Vary pressure and pace until you find what works."], tip:"Slowing down right before the peak makes the finish stronger." },
  { id:"solo-glide", name:"The Long Glide", people:1, cats:["beginner"], diff:1, pose:"soloStand",
    tagline:"Lube changes everything.", steps:["Use a generous amount of lube.","Vary your grip, speed, and angle.","Slow right down each time you near the edge."], tip:"Silicone lube lasts longest and won't dry out mid-session." },
  { id:"solo-mindful", name:"Slow Build", people:1, cats:["intimate"], diff:1, pose:"soloSit",
    tagline:"No goal — just sensation.", steps:["Sit or lie comfortably and breathe.","Touch everywhere *but* the obvious spots first.","Only escalate when you genuinely can't resist."], tip:"Ten minutes of warm-up changes the whole experience." },
  { id:"solo-mirror", name:"Standing Mirror", people:1, cats:["beginner"], diff:1, pose:"soloStand",
    tagline:"Enjoy the view of yourself.", steps:["Stand in front of a mirror.","Take it slow and watch yourself.","Let your free hand roam."], tip:"Making eye contact with yourself feels silly — and is a real confidence boost." },
  { id:"solo-prone", name:"Prone Grinding", people:1, cats:["beginner"], diff:2, pose:"soloProne",
    tagline:"Face-down, grinding into a pillow.", steps:["Lie face-down over a folded pillow.","Grind your hips against the surface.","Adjust the pillow's firmness to change the feel."], tip:"Common but intense — mix it up so you stay sensitive to other touch." },
  { id:"solo-shower", name:"Shower Solo", people:1, cats:["beginner","quickie"], diff:1, pose:"soloStand",
    tagline:"Warm water, standing, easy cleanup.", steps:["Stand under warm water, braced on the wall.","Use the showerhead spray for stimulation.","Keep one hand on the wall for balance."], tip:"Diffuse the spray — never aim a hard jet directly." },
  { id:"solo-edge", name:"Edging Session", people:1, cats:["kinky"], diff:2, pose:"soloRecline",
    tagline:"Build up, back off, repeat.", steps:["Build right up to the edge, then fully stop.","Wait until the urge fades, then start again.","Repeat several rounds before letting go."], tip:"3–5 rounds of edging makes the finish dramatically more intense." },
  { id:"solo-blindfold", name:"Blindfold Solo", people:1, cats:["kinky"], diff:2, needsToy:true, pose:"soloRecline",
    tagline:"Cut sight, amplify everything else.", steps:["Blindfold yourself.","Explore slowly, by feel alone.","Surprise yourself with texture or temperature."], tip:"Not knowing what's next makes every sensation louder." },
  { id:"solo-wand", name:"Wand Play", people:1, cats:["toys"], diff:1, needsToy:true, pose:"soloRecline",
    tagline:"Let a wand vibe do the work.", steps:["Use a wand over (not just on) the most sensitive spot.","A layer of fabric softens it if it's intense.","Move around to find the sweet angle."], tip:"Start on the lowest setting — you can always turn it up." },
  { id:"solo-internal", name:"Internal Toy", people:1, cats:["toys"], diff:2, needsToy:true, pose:"soloRecline",
    tagline:"A dildo or vibe, solo.", steps:["Use plenty of lube.","Insert slowly and find a comfortable angle.","Combine with external stimulation for more."], tip:"A curved toy can reach the g-spot/p-spot — angle toward the front." },
  { id:"solo-dualtoy", name:"Two-Toy Combo", people:1, cats:["toys"], diff:3, needsToy:true, pose:"soloRecline",
    tagline:"Internal and external at once.", steps:["Lube and insert an internal toy.","Add a vibe on the outside.","Sync them, or alternate the two."], tip:"Full + buzz at once is what makes 'blended' finishes happen." },
  { id:"solo-target", name:"Targeted Toy", people:1, cats:["toys"], diff:3, needsToy:true, pose:"soloRecline",
    tagline:"Aim for the g-spot or p-spot.", steps:["Use a curved toy and lots of lube.","Angle toward the front wall (g) or gently inward (p).","Rock and press rather than thrust."], tip:"A slow 'come-hither' motion beats in-and-out for these spots." },
  { id:"solo-plug", name:"Plug Solo", people:1, cats:["toys","anal"], diff:2, needsToy:true, pose:"soloProne",
    tagline:"Wear a plug while you play.", steps:["Lube the plug generously.","Insert slowly; let your body adjust before moving.","Add other stimulation once it feels settled."], tip:"Only use toys with a flared base for anal — no exceptions." },

  // ===================== COUPLES (2) =====================
  { id:"missionary", name:"Missionary", people:2, cats:["beginner","intimate"], diff:1, pose:"missionary",
    tagline:"The timeless face-to-face classic.", steps:["One partner lies back, knees comfortably bent.","The other settles on top, weight on forearms.","A pillow under the hips improves the angle."], tip:"A pillow under the hips changes everything — experiment with height." },
  { id:"coital-alignment", name:"Coital Alignment", people:2, cats:["intimate","beginner"], diff:2, pose:"missionary",
    tagline:"Missionary, rocked for grinding pressure.", steps:["Start in missionary.","The top partner shifts up so hips grind rather than thrust.","Rock together in a slow, steady rhythm."], tip:"This angle hits the clit far more than standard missionary." },
  { id:"splitting-bamboo", name:"Splitting Bamboo", people:2, cats:["athletic"], diff:3, pose:"missionary",
    tagline:"One leg up on a shoulder.", steps:["Receiver on their back, one leg raised onto the giver's shoulder.","Keep the other leg flat.","Enter from the angled side, gently."], tip:"The twist makes a snug, novel angle — ease into it." },
  { id:"the-drill", name:"The Drill", people:2, cats:["athletic","intimate"], diff:3, pose:"missionary",
    tagline:"Legs wrapped tight, deep and close.", steps:["Receiver wraps both legs around the giver's back.","Pull each other in tight.","Use small, deep movements rather than big thrusts."], tip:"More grinding than thrusting — the wrap keeps you locked together." },
  { id:"cowgirl", name:"Cowgirl", people:2, cats:["ontop"], diff:2, pose:"cowgirl",
    tagline:"Top partner sets the pace.", steps:["One partner lies on their back.","The other straddles their hips, sitting upright.","Rock or bounce to control depth and speed."], tip:"Slow circular grinding often beats bouncing for both of you." },
  { id:"asian-cowgirl", name:"Squatting Cowgirl", people:2, cats:["ontop","athletic"], diff:4, pose:"cowgirl",
    tagline:"Feet flat, squatting on top.", steps:["Partner lies back.","The other squats with feet flat — not knees down.","Use the thighs to bounce."], tip:"A real leg workout — alternate with kneeling cowgirl to rest." },
  { id:"prone-cowgirl", name:"Prone Cowgirl", people:2, cats:["ontop","intimate"], diff:2, pose:"cowgirl", flip:true,
    tagline:"Lying flat on top, full-body contact.", steps:["Partner lies back.","The other lies flat along them, legs together.","Grind slowly with the whole body."], tip:"Keeping the legs together makes everything feel tighter." },
  { id:"reverse-cowgirl", name:"Reverse Cowgirl", people:2, cats:["ontop"], diff:2, pose:"reverseCowgirl",
    tagline:"Same idea, facing the other way.", steps:["One lies back; the other straddles facing their feet.","Plant hands on thighs or bed for balance.","Rock to find the angle."], tip:"Lean forward slightly to keep the angle comfortable." },
  { id:"doggy", name:"Doggy Style", people:2, cats:["rear"], diff:2, pose:"doggy",
    tagline:"Deep, primal, a crowd favorite.", steps:["One kneels on all fours.","The other kneels behind, holding the hips.","Lower the chest to change the angle."], tip:"A pillow under the chest lets the receiver relax into it." },
  { id:"prone-bone", name:"Prone Bone", people:2, cats:["rear"], diff:2, pose:"doggy",
    tagline:"Lying flat, entered from behind.", steps:["Receiver lies flat on their stomach, pillow under the hips.","Legs together.","The giver lies over and enters from behind."], tip:"Closing the legs makes it tighter and the angle shallower." },
  { id:"the-turtle", name:"The Turtle", people:2, cats:["rear"], diff:3, pose:"doggy",
    tagline:"Knees tucked, very compact.", steps:["Receiver kneels, then tucks chest down to knees.","The giver enters from behind.","Keep it shallow."], tip:"A deep-feeling angle without deep thrusting." },
  { id:"spooning", name:"Spooning", people:2, cats:["side","beginner","intimate"], diff:1, pose:"spooning",
    tagline:"Lazy, cozy, side-by-side.", steps:["Both lie on their sides, one nestled behind.","Front partner draws their top knee up.","Enter from behind, slow and close."], tip:"Perfect for sleepy mornings — minimal effort, maximum closeness." },
  { id:"the-spork", name:"The Spork", people:2, cats:["side"], diff:3, pose:"spooning",
    tagline:"Side-lying with one leg up.", steps:["Receiver on their side, top leg raised.","Giver kneels astride the lower leg.","Enter from the side."], tip:"Half-spoon, half-missionary — comfy and surprisingly deep." },
  { id:"lotus", name:"The Lotus", people:2, cats:["intimate","seated"], diff:3, pose:"lotus",
    tagline:"Face-to-face, wrapped together.", steps:["One sits cross-legged.","The other climbs into their lap and wraps their legs around.","Rock together rather than thrust."], tip:"Sit against a wall for back support to last longer." },
  { id:"yab-yum", name:"Yab-Yum", people:2, cats:["intimate","seated"], diff:3, pose:"lotus",
    tagline:"Tantric seated embrace.", steps:["One sits cross-legged.","The other sits in their lap, legs wrapped.","Breathe together and rock gently."], tip:"Sync your breathing — it turns sex into something slower and deeper." },
  { id:"reverse-lotus", name:"Reverse Lotus", people:2, cats:["intimate","seated"], diff:3, pose:"lotus", flip:true,
    tagline:"Lotus, facing away.", steps:["One sits.","The other settles into their lap facing away.","Lean back into them and rock together."], tip:"Reach back to hold their neck to stay connected facing away." },
  { id:"butterfly", name:"The Butterfly", people:2, cats:["beginner"], diff:2, pose:"butterfly",
    tagline:"Hips raised at the edge of the bed.", steps:["One lies back with hips at the edge.","They rest their legs on the standing partner's chest/shoulders.","Enter from a slightly raised angle."], tip:"Pick a surface that lines your hips up nicely — height matters." },
  { id:"edge-of-bed", name:"Edge of the Bed", people:2, cats:["seated","beginner"], diff:2, pose:"butterfly",
    tagline:"Receiver at the edge, giver standing or kneeling.", steps:["Receiver lies with hips right at the bed's edge.","Giver stands or kneels at the edge.","Adjust height with a pillow."], tip:"Matching the bed height to hip height is the whole trick." },
  { id:"the-anvil", name:"The Anvil", people:2, cats:["athletic"], diff:3, pose:"anvil",
    tagline:"Missionary, but deeper.", steps:["Start in missionary.","The bottom partner draws knees toward their chest.","Rest those legs on the top partner's shoulders; enter slowly."], tip:"Very deep — communicate and back off if it's ever too much." },
  { id:"viennese-oyster", name:"Viennese Oyster", people:2, cats:["athletic"], diff:5, pose:"anvil",
    tagline:"Knees pinned right back. Very bendy.", steps:["Only if you're very flexible.","Receiver draws knees back beside their head.","Giver supports and enters shallow first."], tip:"Flexibility first — never force the stretch." },
  { id:"the-bridge", name:"The Bridge", people:2, cats:["athletic"], diff:4, pose:"bridge",
    tagline:"An athletic arch. Bring core strength.", steps:["One forms a bridge — hands and feet down, hips lifted.","The other kneels and supports the hips.","Keep it short; it's demanding."], tip:"Warm up first and have a cushion ready for the drop." },
  { id:"the-crab", name:"The Crab", people:2, cats:["athletic"], diff:4, pose:"bridge",
    tagline:"Both leaning back on your hands.", steps:["Both sit leaning back on your hands, feet flat.","Inch together until you meet in the middle.","Small movements only."], tip:"A real core workout — short bursts beat trying to hold forever." },
  { id:"the-pretzel", name:"The Pretzel", people:2, cats:["intimate"], diff:3, pose:"pretzel",
    tagline:"Half-spooning, half facing.", steps:["One lies on their side.","The other straddles the lower leg, upper leg to the side.","Adjust the legs until the depth feels right."], tip:"Combines cowgirl's eye contact with doggy's angle." },
  { id:"pretzel-dip", name:"Pretzel Dip", people:2, cats:["intimate"], diff:3, pose:"pretzel",
    tagline:"Side-on, but still facing each other.", steps:["Receiver on their side.","Giver straddles the lower leg, kneeling.","Enter while keeping eye contact."], tip:"Rare combo: deep angle *and* face-to-face." },
  { id:"pile-driver", name:"Pile Driver", people:2, cats:["athletic"], diff:5, pose:"piledriver",
    tagline:"Expert level. Very deep, very intense.", steps:["Bottom partner's shoulders down, hips lifted vertically.","Support the lower back with hands or a wall.","Top partner squats over and enters from above."], tip:"Only for the flexible and warmed-up. Stop at any discomfort." },
  { id:"spread-eagle", name:"Spread Eagle", people:2, cats:["beginner","kinky"], diff:2, pose:"eagle",
    tagline:"Open, exposed, fully relaxed.", steps:["One lies back and spreads arms and legs wide.","The other lies between their legs.","Pin the spread hands for a playful power edge."], tip:"Pinning wrists (with consent) adds a fun dominant/submissive twist." },
  { id:"chair-facing", name:"The Hot Seat", people:2, cats:["seated"], diff:2, pose:"seated",
    tagline:"One seated, one on their lap.", steps:["One sits on a sturdy chair.","The other straddles them, facing in or out.","Use your feet on the floor to control the bounce."], tip:"A chair without armrests gives way more freedom to move." },
  { id:"lap-dance", name:"Lap Dance", people:2, cats:["seated"], diff:3, pose:"seated",
    tagline:"Facing straddle, full of teasing.", steps:["One sits.","The other straddles them facing in.","Bounce or grind using the floor; tease before you settle in."], tip:"Wrap your arms around each other for leverage and closeness." },
  { id:"standing-doggy", name:"Standing Doggy", people:2, cats:["standing","rear"], diff:2, pose:"standingBent",
    tagline:"Bent over a surface.", steps:["One bends forward, hands on a bed or table.","Feet planted, hips pushed back.","The other stands behind and enters."], tip:"Bracing on a sturdy surface lets you both put real power in." },
  { id:"standing-ff", name:"Standing Face-to-Face", people:2, cats:["standing"], diff:2, pose:"standingWall", flip:true,
    tagline:"Upright, pressed together.", steps:["Both stand; the receiver lifts one leg onto the giver's hip.","Hold each other close.","Brace on a wall if you need it."], tip:"A doorway or counter to lean on makes height differences easy." },
  { id:"the-ballet", name:"The Ballet", people:2, cats:["standing","athletic"], diff:4, pose:"standingBent", flip:true,
    tagline:"Standing, one leg held high.", steps:["Receiver stands on one leg, the other lifted high and held by the giver.","Enter facing them.","Use a wall to keep balance."], tip:"Hold near a wall or chair — balance is the hard part." },
  { id:"against-the-wall", name:"Against the Wall", people:2, cats:["standing","athletic"], diff:5, pose:"standingWall",
    tagline:"Lifted and pinned. Movie-scene energy.", steps:["One is lifted and pressed to the wall.","They wrap their legs around the standing partner.","Let the wall carry most of the weight."], tip:"Sit on a high counter as an easier swap — same vibe, less strain." },
  { id:"the-wheelbarrow", name:"The Wheelbarrow", people:2, cats:["athletic","standing"], diff:5, pose:"wheelbarrow",
    tagline:"One on their hands, the other holding their legs.", steps:["One gets on their hands.","The other lifts their legs like a wheelbarrow.","Enter from behind while holding the thighs."], tip:"Start near a bed so the bottom can rest their upper body on it." },

  // ----- Oral (2) -----
  { id:"sixty-nine", name:"69", people:2, cats:["oral"], diff:3, pose:"sixtynine",
    tagline:"Mutual oral, simultaneously.", steps:["One lies on their back.","The other lies on top, facing the opposite way.","Use forearms to take weight off."], tip:"Side-by-side 69 is comfier and easier to sustain." },
  { id:"side-69", name:"Side 69", people:2, cats:["oral"], diff:3, pose:"sixtynine",
    tagline:"69, lying on your sides.", steps:["Both lie on your sides, head-to-toe.","Rest your legs comfortably.","Give at the same time."], tip:"Far comfier than stacked 69 — you can keep going much longer." },
  { id:"face-sitting", name:"Face Sitting", people:2, cats:["oral","kinky"], diff:2, pose:"facesitting",
    tagline:"The receiving partner takes the throne.", steps:["One lies comfortably on their back.","The other kneels/squats over their face and lowers gently.","The receiver controls pressure with how much weight they rest."], tip:"Agree a tap-out signal so the partner below can always breathe." },
  { id:"reverse-facesit", name:"Reverse Face-Sitting", people:2, cats:["oral"], diff:3, pose:"facesitting", flip:true,
    tagline:"Facing the body, not the face.", steps:["Receiver kneels over the face but faces toward the body.","Lower gently.","The partner below guides with their hands."], tip:"Gives the partner below a great view and easy hand access." },
  { id:"the-throne", name:"The Throne", people:2, cats:["oral"], diff:1, pose:"kneelingOral",
    tagline:"Classic kneeling oral.", steps:["One sits at the edge of a bed or chair.","The other kneels in front.","Use hands together with the mouth; vary the rhythm."], tip:"A cushion under the knees makes it last a lot longer." },
  { id:"standing-oral", name:"Standing Oral", people:2, cats:["oral","standing"], diff:2, pose:"kneelingOral", flip:true,
    tagline:"Quick, hot, and upright.", steps:["One stands, feet planted.","The other kneels in front.","Lean against a wall for stability."], tip:"A pillow for the knees turns minutes into a while." },

  // ----- Anal (2) -----
  { id:"anal-spooning", name:"Anal — Spooning", people:2, cats:["anal","side"], diff:2, pose:"spooning",
    tagline:"The gentlest, most relaxed angle.", steps:["Lube up well first.","Both lie on your sides, one behind.","Enter slowly and shallowly — this position is forgiving."], tip:"Often the easiest for first-timers. Go slow, reapply lube often." },
  { id:"anal-doggy", name:"Anal — Doggy", people:2, cats:["anal","rear"], diff:3, pose:"doggy",
    tagline:"The most common angle for anal.", steps:["Use plenty of lube — the anus doesn't self-lubricate.","Receiver on all fours, fully relaxed.","Enter very slowly, pausing to let muscles adjust."], tip:"Go slow, use lots of lube, reapply often. The receiver sets every limit." },
  { id:"anal-missionary", name:"Anal — Missionary", people:2, cats:["anal"], diff:3, pose:"missionary",
    tagline:"Face-to-face, so you can read each other.", steps:["Lube generously.","Receiver lies back, hips raised on a pillow.","Enter slowly, watching for comfort cues."], tip:"A pillow under the hips relaxes the angle and eases entry." },
  { id:"anal-cowgirl", name:"Anal — Cowgirl", people:2, cats:["anal","ontop"], diff:3, pose:"cowgirl",
    tagline:"Receiver controls every bit of depth.", steps:["Apply plenty of lube.","Giving partner lies back.","Receiver straddles and lowers at their own pace."], tip:"The best beginner-friendly anal angle — the receiver is fully in charge." },
  { id:"anal-reverse", name:"Anal — Reverse Cowgirl", people:2, cats:["anal","ontop","athletic"], diff:4, pose:"reverseCowgirl",
    tagline:"Receiver on top, facing away.", steps:["Lube thoroughly.","Giver lies back; receiver straddles facing away.","Lower very slowly, hands on the thighs for control."], tip:"Even slower than the vaginal version — angle plus depth is a lot." },
  { id:"anal-prone", name:"Anal — Prone", people:2, cats:["anal","rear"], diff:3, pose:"doggy",
    tagline:"Lying flat, entered from behind.", steps:["Lots of lube.","Receiver lies flat, a pillow under the hips.","The giver lies over and enters slowly."], tip:"Lying flat limits depth — many find that more comfortable for anal." },
  { id:"anal-standing", name:"Anal — Standing", people:2, cats:["anal","standing"], diff:4, pose:"standingBent",
    tagline:"Bent over, from behind.", steps:["Generous lube.","Receiver bends over a sturdy surface.","The giver enters very slowly from behind."], tip:"Bracing on a counter lets the receiver push back at their own pace." },

  // ----- Kinky / Toys (2) -----
  { id:"tied-missionary", name:"Tied & Teased", people:2, cats:["kinky","toys"], diff:2, needsToy:true, pose:"eagle",
    tagline:"Wrists restrained, fully at their mercy.", steps:["With consent, restrain one partner's wrists (soft cuffs).","Tease slowly before doing anything else.","Agree a safe word before you start."], tip:"Quick-release cuffs > knots. Never restrain alone, never leave them." },
  { id:"blindfold-play", name:"Blindfolded", people:2, cats:["kinky","intimate"], diff:1, needsToy:true, pose:"missionary",
    tagline:"Take away sight, heighten everything else.", steps:["Blindfold one partner.","Tease with light touch, breath, and temperature.","Keep them guessing what's next."], tip:"Removing one sense makes every other sensation louder." },
  { id:"otk-spanking", name:"Over the Knee", people:2, cats:["kinky"], diff:2, pose:"seated",
    tagline:"Across the lap, with consent.", steps:["Agree the vibe and a safe word.","One drapes over the other's lap.","Start with light, playful smacks and build."], tip:"Warm up gently and check in — it should build, not shock." },
  { id:"hair-pull-doggy", name:"Doggy + Hair Pull", people:2, cats:["kinky","rear"], diff:3, pose:"doggy",
    tagline:"Doggy with a dominant edge.", steps:["In doggy, gather the hair near the scalp — not the ends.","Pull gently and steadily; never jerk.","Pair it with a hand on the hip."], tip:"Hold at the roots near the nape — comfortable and controllable." },
  { id:"couples-vibe", name:"Vibe + PIV", people:2, cats:["toys","ontop"], diff:2, needsToy:true, pose:"cowgirl",
    tagline:"A couples vibrator during the main event.", steps:["Place a slim couples vibe (We-Vibe style) between you.","Settle into cowgirl or missionary.","Let the buzz add to the grind."], tip:"App- or remote-controlled vibes let one partner run the show." },
  { id:"wand-piv", name:"Wand + PIV", people:2, cats:["toys"], diff:2, needsToy:true, pose:"missionary",
    tagline:"A wand vibe through the main event.", steps:["Settle into missionary or cowgirl.","Slip a wand against the clit.","Let it buzz through everything."], tip:"A wide-headed wand is easiest to keep in place while moving." },
  { id:"cock-ring", name:"Cock Ring Play", people:2, cats:["toys"], diff:2, needsToy:true, pose:"missionary",
    tagline:"Firmer, longer, often buzzier.", steps:["Fit a stretchy ring before things get too far along.","Choose a vibrating one to share the buzz.","Any numbness — take it off."], tip:"Never leave a ring on more than about 20 minutes." },
  { id:"pegging", name:"Pegging", people:2, cats:["toys","anal"], diff:3, needsToy:true, pose:"doggy",
    tagline:"Strap-on from behind.", steps:["Lots of lube; receiver on all fours and relaxed.","Enter very slowly with the strap-on.","Build pace only as the receiver asks."], tip:"Communication and lube are everything. Start smaller than you think." },
  { id:"sex-swing", name:"Sex Swing", people:2, cats:["toys","athletic"], diff:4, needsToy:true, pose:"standingWall",
    tagline:"Weightless, endless angles.", steps:["Secure the swing to a rated mount or stand.","The receiver reclines into the straps.","The giver stands and adjusts the height."], tip:"Only hang a swing from a proper mount — never a regular ceiling hook." },
  { id:"double-pen", name:"Double Penetration (Toy)", people:2, cats:["toys","anal"], diff:4, needsToy:true, pose:"doggy",
    tagline:"A partner plus a toy.", steps:["Lots of lube.","Introduce a toy in one opening while the partner takes the other.","Go slow and check in constantly."], tip:"The receiver sets every limit — warm up with just the toy first." },

  // ===================== THREESOME (3) =====================
  { id:"spit-roast", name:"Spit Roast", people:3, cats:["oral","rear"], diff:4, pose:"threeSpit",
    tagline:"One in the middle, attention from both ends.", steps:["The center person is on all fours.","One partner in front (oral), one behind.","Everyone keeps a rhythm that works for the middle."], tip:"The middle person calls the pace — check in with them often." },
  { id:"eiffel-tower", name:"Eiffel Tower", people:3, cats:["oral"], diff:4, pose:"threeSpit",
    tagline:"Two giving, facing each other.", steps:["Middle person on all fours.","One in front, one behind.","The outer two face each other (and can high-five)."], tip:"It's a meme for a reason — but the middle still sets the pace." },
  { id:"lucky-middle", name:"The Lucky Middle", people:3, cats:["anal","rear"], diff:4, pose:"threeSpit",
    tagline:"Giving and receiving at once.", steps:["The middle person enters one partner while being entered by the other.","Coordinate one shared rhythm.","Lube everywhere."], tip:"The middle person drives the pace for the whole chain." },
  { id:"triangle", name:"The Triangle", people:3, cats:["intimate","oral"], diff:3, pose:"threeTriangle",
    tagline:"Three-way, everyone connected.", steps:["Arrange in a loose triangle so everyone can reach someone.","Rotate who gives and receives.","Keep hands busy with whoever's nearest."], tip:"Talk beforehand about who's comfortable doing what — no surprises." },
  { id:"two-on-one", name:"Double Attention", people:3, cats:["oral"], diff:3, pose:"threeTriangle",
    tagline:"Two focus entirely on one.", steps:["One person lies back to receive.","The other two share oral and manual attention.","Switch the lucky one every few minutes."], tip:"Two mouths, one focus — coordinate so you're not in each other's way." },
  { id:"double-cowgirl", name:"Double Cowgirl", people:3, cats:["ontop"], diff:3, pose:"threeTriangle",
    tagline:"Two take turns riding.", steps:["One lies back.","The other two take turns straddling and riding.","The waiting partner kisses or gives oral."], tip:"A timer keeps turns fair and the energy up." },
  { id:"the-sandwich", name:"The Sandwich", people:3, cats:["kinky"], diff:4, pose:"threeTriangle",
    tagline:"One in the middle of two.", steps:["One lies on their back.","The middle person lies on top of them.","The third enters the middle person from behind."], tip:"Lots of lube and patience — the middle person is doing the most." },
  { id:"three-oral-chain", name:"Oral Chain (3)", people:3, cats:["oral"], diff:3, pose:"threeTriangle",
    tagline:"Each focuses on the next.", steps:["Line up so each person attends to the one ahead.","Find a comfy curl.","Everyone gives and gets at once."], tip:"Side-lying makes the chain easy to hold." },
  { id:"the-voyeur", name:"The Voyeur", people:3, cats:["intimate"], diff:2, pose:"threeTriangle",
    tagline:"Two play, one watches — then joins.", steps:["Two start together.","The third watches and touches themselves.","They join when invited."], tip:"Agree the 'join' signal first — anticipation is the fun part." },
  { id:"three-cuddle", name:"Three-Way Tangle", people:3, cats:["intimate","kinky"], diff:2, pose:"threeTriangle",
    tagline:"Hands and mouths everywhere.", steps:["Pile in close so everyone can touch everyone.","No fixed roles — follow the energy.","Check in often."], tip:"A relaxed way to start before settling into a position." },

  // ===================== FOURSOME (4) =====================
  { id:"two-couples", name:"Side-by-Side Couples", people:4, cats:["beginner"], diff:3, pose:"fourSquare",
    tagline:"Two pairs, sharing the same space.", steps:["Two couples set up next to each other.","Match a rhythm — or deliberately don't.","Watching each other is half the fun."], tip:"A great soft-start for groups — everyone stays with their own partner." },
  { id:"partner-swap", name:"Partner Swap", people:4, cats:["beginner"], diff:3, pose:"fourSquare",
    tagline:"Trade partners, keep it playful.", steps:["Agree the swap and any limits in advance.","Pair off with the new partner.","Check in with everyone as you go."], tip:"Set the ground rules while everyone's still clear-headed." },
  { id:"two-couples-69", name:"Side-by-Side 69", people:4, cats:["oral"], diff:4, pose:"fourSquare",
    tagline:"Two pairs, mutual oral.", steps:["Two couples each get into 69.","Line up so you can watch each other.","Race or sync — your call."], tip:"A relaxed, low-pressure way to share a space." },
  { id:"daisy-four", name:"Daisy Chain (4)", people:4, cats:["oral"], diff:4, pose:"fourSquare",
    tagline:"A four-person oral loop.", steps:["Curl into a connected ring of four.","Everyone gives to the person ahead.","Adjust until each link is comfortable."], tip:"Lie on your sides — sitting up gets tiring fast." },
  { id:"group-oral", name:"Oral Circle", people:4, cats:["oral"], diff:4, pose:"fourSquare",
    tagline:"Everyone in, taking turns.", steps:["Gather in a loose circle.","Rotate who's the focus.","Keep hands and mouths busy with the nearest person."], tip:"A 'rotate on a timer' rule keeps it fair and flowing." },
  { id:"double-spitroast", name:"Double Spit Roast", people:4, cats:["oral","rear"], diff:5, pose:"fourSquare",
    tagline:"Two middles, attention from both ends.", steps:["Two people on all fours, side by side.","Partners work the front and back of each.","Keep a shared, gentle rhythm."], tip:"Lots of lube and frequent check-ins down the line." },
  { id:"group-grind", name:"Group Grind", people:4, cats:["kinky"], diff:3, pose:"fourSquare",
    tagline:"Full-contact pile, no fixed roles.", steps:["Four bodies, hands everywhere.","Read the room and follow the energy.","Consent for each new touch."], tip:"A soft-start for groups — easy to dial up or down." },
  { id:"four-voyeur", name:"Two Play, Two Watch", people:4, cats:["intimate"], diff:2, pose:"fourSquare",
    tagline:"One pair performs, one pair watches.", steps:["One couple takes center stage.","The other watches and warms up.","Swap roles when you like."], tip:"Watching (and being watched) is a thrill all on its own." },

  // ===================== ORGY (5+) =====================
  { id:"the-pile", name:"The Pile", people:5, cats:["kinky"], diff:4, pose:"orgyPile",
    tagline:"Everyone in a warm tangle.", steps:["Gather close on a big soft surface.","Hands, mouths, and bodies everywhere — go with the flow.","Check in often; anyone can step out anytime."], tip:"Lay down extra towels and keep water nearby — groups get sweaty." },
  { id:"cuddle-puddle", name:"Cuddle Puddle", people:5, cats:["intimate"], diff:3, pose:"orgyPile",
    tagline:"Soft, slow, sensory group.", steps:["Pile together gently.","Focus on touch, kissing, and closeness over anything fast.","Anyone can drift in or out."], tip:"A warm, low-key start that lets a group ease in." },
  { id:"the-rotation", name:"The Rotation", people:5, cats:["kinky"], diff:4, pose:"orgyPile",
    tagline:"Partners swap on a signal.", steps:["Everyone pairs off.","On the agreed signal, rotate partners.","Keep consent flowing with each swap."], tip:"A 'rotate every few minutes' rule keeps it fair and fun." },
  { id:"free-for-all", name:"Free For All", people:5, cats:["kinky"], diff:3, pose:"orgyPile",
    tagline:"No formation — just vibes.", steps:["No fixed roles; pair and re-pair freely.","Join where you're wanted.","Consent for each new pairing, every time."], tip:"Establish a group safe word everyone knows before starting." },
  { id:"the-circle", name:"The Circle", people:5, cats:["oral"], diff:4, pose:"orgyRing",
    tagline:"A ring of giving and receiving.", steps:["Everyone forms a connected ring.","Each person attends to a neighbour.","Rotate the direction now and then."], tip:"Agree a signal for 'rotate' so it stays coordinated." },
  { id:"daisy-group", name:"Group Daisy Chain", people:5, cats:["oral"], diff:5, pose:"orgyRing",
    tagline:"Everyone linked at once.", steps:["Curl into one big connected chain.","Each gives to the next.","Adjust until every link works."], tip:"Side-lying on a big soft surface is the only comfy way." },
  { id:"the-train", name:"The Train", people:5, cats:["rear"], diff:5, pose:"orgyRing",
    tagline:"A line, each behind the next.", steps:["Line up, each person behind the one ahead.","Everyone keeps a shared, gentle rhythm.","The front and back set the pace."], tip:"Lube for everyone, and frequent check-ins down the line." },
  { id:"group-focus", name:"The Spotlight", people:5, cats:["oral","kinky"], diff:4, pose:"orgyPile",
    tagline:"The whole group focuses on one.", steps:["One person lies back as the focus.","Everyone else gives attention at once.","Rotate the spotlight regularly."], tip:"Take turns being the center — everyone gets a moment." }
];
